### ISSUE TITLE
Conflict with eslint plugin '@vue/typescript'

### ISSUE THREAD

**Issue by r0skar** [dwightjack/eslint-plugin-vue-types#1]
First of all: Thanks for the great `vue-types` plugin!

Using `@vue/cli-plugin-eslint 3.0.0-beta.15`, I have installed `eslint-plugin-vue-types` alongside with `vue-types` and have configured Eslint like this:

```javascript
  extends: [
    'plugin:vue/essential',
    '@vue/prettier',
    '@vue/typescript',
    'plugin:vue-types/strongly-recommended'
  ],
```

I get this error:

```bash
error: Prop 'href' requires default value to be set (vue-types/require-default-prop) at src/components/_BaseLink.vue:21:5:
  19 | export default Vue.extend({
  20 |   props: {
> 21 |     href: VueTypes.string.def('test')
     |     ^
  22 |   }
  23 | })
  24 | </script>
```

Once I removed `'@vue/typescript'` everything is working fine.

So it seems there is a conflict between the two plugins?

**Comment by dwightjack** [comment]
Hi,

sorry for the late reply. Are you still experiencing this issue? I've worked with a similar setup lately and didn't had this issue.

**Comment by r0skar** [comment]
Hey,

I did not use Vue for quite some time. Not sure the problem still exists. Feel free to close the issue for now. I guess with Vue 3 the whole Vue+TS setup is going to change anyway.

**Comment by dwightjack** [comment]
Ok cool. Sorry again for the (too) late reply and for your feedback. 👍
