### ISSUE TITLE
custom definition issue

### ISSUE THREAD

**Issue by MatteoGabriele** [dwightjack/eslint-plugin-vue-types#4]
Hi Marco, thanks for the plugin again.
I am implementing a more "strong" linter and i am finding issues with the vue-types plugin.
I have a folder where i store common types and re-use them across the application: now it's kind of an issue with the linter because the linter think i'm missing the prop definition.

the only whitelisting feature doesn't really scale tbh. is there another way to do this without whitelisting all the files I am using?

**Comment by dwightjack** [comment]
Hi, if I'm getting this right you are storing some type configurations to be reused in multiple components.

The best solution here would be to store them under a common namespace and whitelist that namespace in the [plugin configuration](https://github.com/dwightjack/eslint-plugin-vue-types#custom-vue-types-namespaces). Something like this:

```js
import VueTypes from 'vue-types';

const myTypes = {
  user: VueTypes.shape({ ... }),
  ...
};

export default myTypes;
```

Alternatively, you can use the `VueTypes.extend` method to add custom types to VueTypes itself. I've just released a new feature that lets you use VueTypes complex types as the base for a custom type ([docs](https://github.com/dwightjack/vue-types#inherit-from-vuetypes-types)).
